### ISSUE TITLE
[Bug] TagsInput is not displayed properly on mobile device

### ISSUE THREAD

**Issue by arlejeun** [creativetimofficial/ct-nuxt-argon-dashboard-pro#10]
### Version
latest
### Reproduction link
https://demos.creative-tim.com/nuxt-argon-dashboard-pro/documentation/plugins/tags-input.html
### Operating System
MAC OS
### Device
iPhone
### Browser & Version
Chrome latest
### Steps to reproduce
Add tags to the tag inputs.
Open your webpage with your mobile device and display is not responsive
### What is expected?
To be responsive and display tags in the next row similar to the multi-select behavior
### What is actually happening?
The component is not usable with a mobile device because up to a point we can't add a new tag

---

**Comment by cristijora** [comment]
This issue was fixed in version 1.2.0 along with other fixes & improvements.
For more details check the detailed [changelog here](https://demos.creative-tim.com/nuxt-argon-dashboard-pro/documentation/changelog.html)

**Comment by arlejeun** [comment]
Great news! Thanks Cristi.. I’m looking forward to trying it

**Comment by arlejeun** [comment]
Hi Cristi,

I just upgraded your version 1.2.0 but I can no longer update the form now.
Please advise. I've just looked at your preview and the result is the same.
We can no longer update the form input.
Do you have a fix?

**Comment by arlejeun** [comment]
Hi Cristi,

Happy New Year. I upgraded to version 1.2.0 but I still have the strange behavior on Mobile devices.
Looking at the screenshot, it should go to the line and enable me to enter another tags.

![image](https://user-images.githubusercontent.com/4977163/71832992-b091bc00-3071-11ea-86ec-b1691e2fa8c5.png)

**Comment by arlejeun** [comment]
Please reopen this issue
